name: executable
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  redux: ^5.0.0
  flutter_redux: ^0.10.0

  data:
    path: ../data
  domain:
    path: ../domain
  presentation:
    path: ../presentation
  localizations:
    path: ../localizations
  clean_redux: ^0.3.3
  url_strategy: ^0.3.0
  supabase_flutter: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:

  uses-material-design: true
