name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  intl: ^0.19.0
  uuid: ^4.5.1
  rxdart: ^0.27.7
  clean_redux: ^0.3.3
  equatable: ^2.0.5

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
