import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:google_fonts/google_fonts.dart';

final lightTheme = FlexThemeData.light(
  scheme: FlexScheme.redWine,
  surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
  blendLevel: 20,
  appBarStyle: FlexAppBarStyle.primary,
  appBarElevation: 9.5,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 10,
    blendOnColors: false,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    defaultRadius: 12.0,
    textButtonRadius: 20.0,
    filledButtonRadius: 20.0,
    elevatedButtonRadius: 20.0,
    outlinedButtonRadius: 20.0,
    outlinedButtonBorderWidth: 2.0,
    outlinedButtonPressedBorderWidth: 3.5,
    toggleButtonsRadius: 24.0,
    toggleButtonsBorderWidth: 2.5,
    inputDecoratorRadius: 20.0,
    alignedDropdown: true,
    useInputDecoratorThemeInDialogs: true,
    snackBarRadius: 10,
    bottomSheetRadius: 32.0,
  ),
  useMaterial3ErrorColors: true,
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  fontFamily: GoogleFonts.rubik().fontFamily,
);

final darkTheme = FlexThemeData.dark(
  scheme: FlexScheme.redWine,
  surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
  blendLevel: 12,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 20,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    defaultRadius: 12.0,
    textButtonRadius: 20.0,
    filledButtonRadius: 20.0,
    elevatedButtonRadius: 20.0,
    outlinedButtonRadius: 20.0,
    outlinedButtonBorderWidth: 2.0,
    outlinedButtonPressedBorderWidth: 3.5,
    toggleButtonsRadius: 24.0,
    toggleButtonsBorderWidth: 2.5,
    inputDecoratorRadius: 20.0,
    alignedDropdown: true,
    useInputDecoratorThemeInDialogs: true,
    snackBarRadius: 10,
    bottomSheetRadius: 32.0,
  ),
  useMaterial3ErrorColors: true,
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  fontFamily: GoogleFonts.rubik().fontFamily,
);
